.travis.yml, tox.ini
Target Python38 for testing as this module may be senstive to changes in the re module. Test, but do not fail on Py38 as we are only hoping to expose issues, not hold up merges or releases.
=> Test Python38

docs/src/markdown/changelog.md, wcmatch/__meta__.py, wcmatch/_wcparse.py
- Fix an offset issue when processing an absolute path pattern in `glob`
on Linux or macOS.
- Fix an issue where the `glob` command would use `GLOBSTAR` logic on
`**` even when `GLOBSTAR` was disabled.
=> Glob bug fixes

docs/src/markdown/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, tests/test_fnmatch.py, tests/test_glob.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/wcmatch.py
Instead of deprecating defaults for exclusions, make an official flag
called NEGATEALL (rename from NEGDEFAULT). But in paths, always apply
`GLOBSTAR` to the default pattern.
=> Don't deprecate exclusion defaults, but provide an official flag

docs/src/markdown/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, docs/src/markdown/wcmatch.md, tests/test_fnmatch.py, tests/test_glob.py, tests/test_globmatch.py, tests/test_wcmatch.py, wcmatch/__meta__.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/wcmatch.py
This implements case sensitive matching and globbing in Windows. As Windows can enable case sensitivity on folders etc., or sometimes access shares that are case sensitive, it makes sense to expose case sensitive matching and globbing on Windows.
Despite the fact that folders can be case sensitive, drives still aren't, and it makes no sense to enforce that behavior on the drive letter portion of a path. In addition to that, UNC `\\host\share` portions are usually treated insensitively. While it may be possible the host name is sensitive, there is no real way to quickly and easily get that true case at this time, so UNC host/share portion will be treated as a drive and be insensitive as well while the tail portion will be sensitive.
Now that we have explicit flags for forcing Linux/Unix …
=> Windows case sensitivity flag

docs/src/markdown/changelog.md, tests/test_glob.py, wcmatch/__meta__.py, wcmatch/glob.py
- Regression for root level literal matches in `glob`.
- Bug where `glob` would mistakenly abort if a pattern started with a
literal file or directory and could not match a file or directory.
This caused subsequent patterns in the chain to not get evaluated.
=> Fix regression with literal start pattern and multiple patterns in glob

.travis.yml
Test if Github CI supports Py38. If it doesn't, we may have to use Travis as we formally are supporting Py38.
=> Test if Github CI supports Py38

docs/src/markdown/changelog.md, docs/src/markdown/pathlib.md, docs/src/markdown/wcmatch.md, wcmatch/__meta__.py, wcmatch/glob.py, wcmatch/wcmatch.py
We need to grab all the files and folder names under a folder in one
batch to avoid leaking file descriptors in glob.
=> Avoid risk of leaking file descriptors

docs/src/markdown/changelog.md, tests/test_pathlib.py, wcmatch/__meta__.py, wcmatch/glob.py, wcmatch/pathlib.py
This should fix all pathlib issues related to relative path handling.
Glob now handles any base path just like it would for the CWD.
Negate patterns were broken in pathlib due to the fact that there paths
were compared to the exclusion pattern not as relative paths to the
base, but as paths including the base. This keeps the whole glob
pipeline dealing with paths relative the base only. The base will never
come into play except at key points where the file system must be
accessed: scandir, lexists, etc.
Glob will now return the paths relative to the main path, and pathlib
will simply create a new pathlib object by joining the relative segment.
=> Fix pathlib handling of negate patterns

docs/src/markdown/pathlib.md
Python's Pathlib match and wcmatche's Pathlib match handle dot
directories a bit different. Document this difference.
=> Document relative path difference in behavior of Pathlib's match.

wcmatch/_wcparse.py
Once upon a time, the internal glob pattern was broken down into literal
parts containing consecutive literal file parts, and then magic parts.
Now there are no consecutive literals contained in a single part, but
each literal directory/file are contained within their own part. Update
docstring to reflect that.
=> Fix internal comment on glob pattern breakdown

docs/src/dictionary/en-custom.txt, docs/src/markdown/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, docs/src/markdown/pathlib.md, docs/src/markdown/wcmatch.md, tests/test_fnmatch.py, tests/test_glob.py, tests/test_globmatch.py, tests/test_pathlib.py, tests/test_wcmatch.py, tests/test_wcparse.py, wcmatch/__meta__.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/pathlib.py, wcmatch/wcmatch.py
- BRACE is now processed before SPLIT.
- We now optimize out duplicate patterns and reduce duplicate returns..
- We also now limit patterns to 1000. This includes patterns directly passed in, and patterns indirectly included via expansion by BRACE and/or SPLIT.
- Added new option NOUNIQUE to turn off the above "unique" pattern/result behavior above. Only affects glob, iglob, rglob functions.
Fixes #97
Fixes #99
=> Process BRACE before SPLIT and refactor SPLIT some

wcmatch/__meta__.py, wcmatch/glob.py
No need to go through _glob_dir. We can go through _iter
directly. Also don't need to calculate base and dir name.
We can simply pass _iter a None for the path which forces
root_dir to get used and just compare the returned names.
=> glob: Simplify start path logic

wcmatch/glob.py
When under the `dir_only` conditional block, it can be assumed
that all directories returned are directories. If this assumption
is not true, it means there is a bug in the code. Eliminate the
redundant check of whether the file in question is a directory
in the main, non-magic, directory only loop.
=> Remove unnecessary directory check from glob

docs/src/markdown/about/changelog.md, tests/test_glob.py, wcmatch/__meta__.py, wcmatch/glob.py
Doing some evaluation and noticed that `**` and `**/*` wasn't quite behaving correctly, but this was only with `glob` and not `globmatch`. Basically `**/*` was not matching a symlinked folder. This is because when we iterated through folders with `**`, we did not return symlinks to directories if `FOLLOW` was not enabled. So in case of `**/*` which should have matched the directory, but didn't.
Tests have been added to ensure this doesn't break in the future.
=> Glob should match Bash 5.0 behavior in regard to link following

docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, docs/src/markdown/glob.md, docs/src/markdown/pathlib.md, docs/src/markdown/wcmatch.md, mkdocs.yml, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/pathlib.py, wcmatch/wcmatch.py
Pathlib should not be limited by dotfiles on the left as evaluation
order is from right to left.
=> Fix pathlib match behavior related to dot files

docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, docs/src/markdown/pathlib.md, docs/src/markdown/wcmatch.md, tests/test_fnmatch.py, tests/test_globmatch.py, tests/test_wcparse.py, wcmatch/__meta__.py, wcmatch/_wcparse.py, wcmatch/glob.py
If at anytime, !( is found at the start of a path, and NEGATE and
EXTGLOB are enabled at the same time, the pattern will be parsed as
EXTGLOB. If the parse fails to find a valid EXTGLOB pattern, !( will
be treated as a literal !( and not as a NEGATE pattern.
=> Basic handling of ! and !( at start of file path

docs/src/markdown/about/changelog.md, tests/test_globmatch.py, tests/test_pathlib.py, wcmatch/_wcparse.py, wcmatch/util.py
Users can now escape any characters in Windows drives. This is done
so:
1. users can properly escape `{}|` characters in Windows drives.
2. also to be forgiving if a user gets confused and thinks they should
escape special chars in Windows drives.
Any escapes will be treated simply as the character itself.
=> Refactor escape logic for Windows drives

docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, docs/src/markdown/about/release.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, docs/src/markdown/pathlib.md, docs/theme/main.html, mkdocs.yml, requirements/docs.txt, tests/test_glob.py, wcmatch/_wcparse.py, wcmatch/glob.py
- New "scandir" logic should not affect pattern handling
- pathlib.match should not following symlinks of the leftmost portion
of what was matched.
=> "scandir" and symlink following fix

docs/src/markdown/about/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, docs/src/markdown/wcmatch.md, tests/test_wcmatch.py, wcmatch/wcmatch.py
The `WcMatch`'s `on_init` will now only accept keyword arguments. `__init__` will still take default arguments as positional arguments or keyword arguments, but you can no longer specify custom positional arguments as this created unnecessary complexity. For the average user, this change will be backwards compatible, but if you were overriding with the `on_init` hook, or trying to handle custom positional arguments, you will have to update your usage accordingly.
Closes #142
=> Require args to be kwargs in WcMatch class' on_init

docs/src/markdown/about/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, requirements/setup.txt, tests/test_fnmatch.py, wcmatch/_wcparse.py, wcmatch/posix.py
While we had intended to use the Unicode tables, we never actually did,
and no one ever noticed, not even me (until now). As we've stuck with
the ASCII tables all this time, and it has been more than sufficient,
port that logic into wcmatch directly and drop backrefs. Update docs
so there is no confusion.
Fixes #144
=> Drop requirement for backrefs as the Unicode tables were never used

docs/src/markdown/about/changelog.md, tests/test_glob.py, tests/test_globmatch.py, wcmatch/__meta__.py, wcmatch/_wcparse.py, wcmatch/glob.py, wcmatch/util.py
- Use `os.fspath` to convert path-like objects to string, whatever the
preferred return for `os.path` is what Wildcard Match will accept.
Don't try to convert paths via `__str__` or `__bytes__`.
- Better checking of types to ensure consistent failure if the path,
pattern, or root directory of are not all of type `str` or `bytes`.
=> Better checking and failure of mismatched str and byte types in glob

docs/src/markdown/about/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, tests/test_glob.py, wcmatch/glob.py
The same can be accomplished simply by using `codecs.decode(string, 'unicode_escape')` and then using `escape`. Considering that this was added and I've never actually used it, coupled with the fact that this is possible in a fairly trivial manner without this API function, I can't see a need for carrying this around any longer.
=> Deprecate raw_escape

tests/test_fnmatch.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py
As we are deprecating raw_escape in glob, there is no reason to release
fnmatch with raw_escape.
=> Remove raw_escape from fnmatch

wcmatch/_wcparse.py, wcmatch/util.py
Consistently use `.format()` string format instead of `%`.
There are probably few places where we can utilize format strings as
most of the time the replacements are deferred, but in the future, maybe
we will convert some of the cases from `.format()` to format strings.
=> Drop use of percent string format

tests/test_glob.py
Recently a fix for the tests related to tilde expansion was added for
Linux. While this behavior accommodated Linux pretty well, in some
cases, on Windows, the fix could cause the test to fail. Only use the
adjustment for non-Windows systems.
=> Fix user handling in tilde test for Windows

README.md, docs/src/markdown/about/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/index.md
A few cases where characters appear to be transposed.
=> typos (fnamtch => fnmatch)

docs/src/markdown/about/changelog.md, tests/test_glob.py, wcmatch/__meta__.py, wcmatch/_wcparse.py, wcmatch/glob.py
- Windows drives should be normalized.
- Fix internal logic when handling an ambiguous drive on windows, `r'\\*'` should resolve the same as `'/*'`.
Resolves #197 
Resolves #196
=> Fix Windows drive normalization and pattern indexing with implied drives

wcmatch/_wcmatch.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/pathlib.py, wcmatch/util.py, wcmatch/wcmatch.py
Since we use `from __future__ import annotations` type annotations will be ignored as strings. We can use `type | None` even on older Python versions.
=> Replace use of Optional in type annotations

docs/src/markdown/wcmatch.md
According to the source code, the doc misses a "S".
https://github.com/jfcherng/wcmatch/blob/24bf989afb8b0a69bba22877ecf2dd832fdd8637/wcmatch/wcmatch.py#L35
=> Fix wcmatch docs: SYMLINK => SYMLINKS

docs/src/markdown/about/changelog.md, tests/test_fnmatch.py, wcmatch/__meta__.py, wcmatch/_wcparse.py
=> Fix extmatch negation case

docs/src/markdown/about/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, hatch_build.py, pyproject.toml, tests/test_glob.py, wcmatch/__meta__.py, wcmatch/_wcmatch.py, wcmatch/_wcparse.py, wcmatch/glob.py, wcmatch/pathlib.py, wcmatch/posix.py, wcmatch/util.py
- Support Py 3.13
- Remove deprecated `raw_escape`
- Remove casting which incurs a performance cost for little gain. Once that cannot easily be resolved, just ignore the mypy error.
- Update formatted strings to f-string (where possible)
=> Add support for Py 3.13

docs/src/markdown/about/changelog.md, docs/src/markdown/glob.md, tests/test_glob.py, tests/test_globmatch.py, wcmatch/__meta__.py, wcmatch/_wcmatch.py, wcmatch/glob.py
Some fixes to globmatch symlinks are also included
Fixes #222
=> `FOLLOW` should control traversal of symlinks, not return of them

docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, docs/src/markdown/glob.md, docs/src/markdown/pathlib.md, tests/test_fnmatch.py, tests/test_glob.py, tests/test_globmatch.py, tests/test_pathlib.py, wcmatch/_wcparse.py, wcmatch/glob.py, wcmatch/pathlib.py
=> Add support for Zsh style `***`

README.md, docs/src/dictionary/en-custom.txt, docs/src/markdown/about/changelog.md, docs/src/markdown/about/release.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, docs/src/markdown/pathlib.md, docs/src/markdown/wcmatch.md, tests/test_fnmatch.py, tests/test_glob.py, tests/test_globmatch.py, wcmatch/__meta__.py, wcmatch/_wcmatch.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/pathlib.py, wcmatch/posix.py
=> Add option to get a precompiled matcher object
