docs/src/markdown/changelog.md, docs/src/markdown/wcmatch.md, tests/test_fnmatch.py, tests/test_glob.py, tests/test_globmatch.py, tests/test_wcmatch.py, tests/test_wcparse.py, wcmatch/_wcparse.py, wcmatch/file_hidden.py, wcmatch/glob.py, wcmatch/util.py, wcmatch/wcmatch.py
Test known corner cases to ensure proper behavior. Fix related issues.
=> Unittests work

.travis.yml, appveyor.yml, docs/src/markdown/changelog.md, docs/src/markdown/wcmatch.md, wcmatch/wcmatch.py
=> wcmatch will not allow EXTGLOB

docs/src/markdown/changelog.md, docs/src/markdown/glob.md, setup.py, wcmatch/__version__.py
Setup doesn't need the requirements, install does. Thanks to @gregplaysguitar. Ref #12.
=> Fix install requirements

README.md, docs/src/markdown/changelog.md, tests/test_fnmatch.py, wcmatch/__version__.py, wcmatch/wcmatch.py
Also clean up some test comments. Ref #15.
=> Ensure we check that override return is not None and not falsy

docs/src/markdown/changelog.md, tests/test_fnmatch.py, tests/test_glob.py, tests/test_globmatch.py, wcmatch/_wcparse.py, wcmatch/file_hidden.py
=> Fix negate not evaluating full path

.travis.yml, docs/src/markdown/changelog.md, requirements/setup.txt, setup.py, tox.ini, wcmatch/__meta__.py
=> Add Python 3.8 support

wcmatch/__meta__.py, wcmatch/glob.py
This consolidates the logic of shallow and deep globbing as they are
mostly the same. _glob_dir will now accept a 'deep' parameter when we
desire deep functionality.
=> Refactor internal glob shallow and glob deep as one function

docs/src/markdown/changelog.md, wcmatch/__meta__.py, wcmatch/wcmatch.py
=> Defer hidden call until after file pattern matching for performance

docs/src/markdown/changelog.md, docs/src/markdown/wcmatch.md, tests/test_wcmatch.py, wcmatch/wcmatch.py
=> Add on_reset methods to WcMatch class and deprecate kill and reset

docs/src/markdown/changelog.md, docs/src/markdown/glob.md, tests/test_glob.py, tests/test_globmatch.py, wcmatch/_wcparse.py, wcmatch/glob.py
=> Add `MARK` flag to mark directories with trailing slashes

docs/src/markdown/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, tests/test_fnmatch.py, tests/test_glob.py, tests/test_globmatch.py, tests/test_wcmatch.py, wcmatch/__meta__.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/util.py, wcmatch/wcmatch.py
=> Less strict exclusion patterns

docs/src/dictionary/en-custom.txt, docs/src/markdown/changelog.md, docs/src/markdown/glob.md, docs/src/markdown/wcmatch.md, tests/test_glob.py, tests/test_globmatch.py, wcmatch/_wcparse.py, wcmatch/glob.py
=> Add option to restrict directories from glob matches and searches

docs/src/markdown/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, tests/test_fnmatch.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/wcmatch.py
=> Reverse output of translated exclusion patterns

docs/src/markdown/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, wcmatch/__meta__.py
Documentation cleanup and bump version
Closes #54
=> Prep 4.0.0

docs/src/markdown/changelog.md, wcmatch/__meta__.py, wcmatch/glob.py
There was a regression with glob exclusion patterns, specifically ones that use braces. The braces were not getting resolved.
=> Fix exclusion patterns in glob that use braces

docs/src/markdown/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, docs/src/markdown/pathlib.md, docs/src/markdown/wcmatch.md, tests/test_fnmatch.py, tests/test_glob.py, tests/test_globmatch.py, wcmatch/__init__.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/pathlib.py, wcmatch/util.py, wcmatch/wcmatch.py
=> Add root_dir option and support for path-like object inputs

requirements/test.txt, tests/test_fnmatch.py
=> Use builtin mock

docs/src/markdown/about/changelog.md, wcmatch/__meta__.py
Assuming nothing else comes up, this will probably be everything in the 6.0.3 release.
=> Prep for 6.0.3 release

docs/src/markdown/about/changelog.md, wcmatch/__meta__.py, wcmatch/_wcparse.py
Minor cleanup. Bump version. Adjust some phrasing in changelog.
=> Prep for 8.1.0 release

docs/src/markdown/about/changelog.md, wcmatch/__meta__.py, wcmatch/glob.py
=> Fix unique tracking with case sensitive vs insensitive

wcmatch/_wcmatch.py, wcmatch/_wcparse.py, wcmatch/glob.py, wcmatch/util.py
- Move match logic to _wcmatch
- Move all "glob" logic to glob
=> Refactoring

.github/workflows/build.yml, .github/workflows/deploy.yml, tox.ini, wcmatch/pathlib.py, wcmatch/util.py
=> Attempt to test Python 3.10 with fix for pathlib

.coveragerc, docs/src/markdown/about/changelog.md, docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, docs/src/markdown/pathlib.md, tests/test_fnmatch.py, tests/test_glob.py, tests/test_globmatch.py, tests/test_pathlib.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/pathlib.py
=> Add exclude option

docs/src/markdown/fnmatch.md, docs/src/markdown/glob.md, mkdocs.yml
=> Improve documentation on Windows separators

wcmatch/__meta__.py, wcmatch/_wcmatch.py, wcmatch/_wcparse.py, wcmatch/fnmatch.py, wcmatch/glob.py, wcmatch/pathlib.py, wcmatch/posix.py, wcmatch/util.py, wcmatch/wcmatch.py
=> Annotation cleanup

docs/src/markdown/about/changelog.md, tests/test_glob.py, tests/test_pathlib.py, wcmatch/__meta__.py, wcmatch/glob.py, wcmatch/pathlib.py
=> Fix magic/non-magic mix handling

LICENSE.md, docs/src/markdown/about/changelog.md, mkdocs.yml, wcmatch/__meta__.py, wcmatch/glob.py
=> Fix issue with type checking in glob

.github/workflows/build.yml, .github/workflows/deploy.yml, pyproject.toml, wcmatch/pathlib.py, wcmatch/util.py
=> Fix build environment and make adjustments for Python 3.13
